### ISSUE TITLE
HyperFastClassifier not sklearn.clone safe

### ISSUE THREAD

**Issue by amueller** [AI-sandbox/HyperFast#1]
Hey!
So it looks like ``HyperFastClassifier`` doesn't satisfy the scikit-learn API, in particular clone doesn't seem to work:

```python
import torch
import numpy as np
from hyperfast import HyperFastClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.base import clone

# Set the device
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, stratify=iris.target)
# Initialize HyperFast
model = clone(HyperFastClassifier(device=device))

# Generate a target network and make predictions
model.fit(X_train, y_train)
```
this fails.

That unfortunately means that the scikit-learn cross-validation methods won't work (or any of the scikit-learn meta-estimators).
You can check if your model satisfies the sklearn API by running [check_estimator](https://scikit-learn.org/stable/modules/generated/sklearn.utils.estimator_checks.check_estimator.html).

**Comment by davidbonet** [comment]
Hi, thanks for pointing this out! We've fixed the compatibility problem with the scikit-learn API. Please update to the latest version, the clone function and the rest of functionalities should now work with our classifier. 
Let us know if you encounter any more issues!

**Comment by amueller** [comment]
Great thank you! I took a short break in experimenting with it but I'll get back to it soon!
