### ISSUE TITLE
More notes on scikit-learn compatibility

### ISSUE THREAD

**Issue by amueller** [AI-sandbox/HyperFast#4]
Hey!
So I noticed two more slight mismatches wrt scikit-learn API: first, there's no ``score`` method, which should just be accuracy. You can get that from inheriting from BaseEstimator, I think?
The second is that you take ``cat_features`` in ``fit``, not in ``__init__`` which prevents using the model with scikit-learn cross-validation and pipelining easily. This is a bit annoying for users, hopefully eventually we'll get a better treatment of categorical variables in scikit-learn.

I also just noticed that ``cat_features`` has a mutable default value of ``[]`` which is dangerous. I don't think you ever modify it, but that means that all estimators share a single instance of this list if none was passed.

**Comment by davidbonet** [comment]
Hey,
Thank you for your valuable feedback.

Regarding the `score` method, we have now inherited from `ClassifierMixin`, which has the `score` functionality.

Concerning `cat_features`, our current HyperFast design is optimized for a scenario where you initialize `HyperFastClassifier` just once, and deploy the main networks (`fit`) many times on new datasets. But you do have to modify `cat_features` for every new dataset specifying the categorical features indeces, along `X_train` and `y_train` every time. Specifying `cat_features` can only be skipped in very particular cases like numerical features-only, or on the indices of binary categorical feature that are already one-hot encoded (i.e., [0 1]), which is the case for the hapmap dataset given in `data/`. Also, re-initializing the model for every new dataset would lead to significantly slower execution and a less optimal user experience, as the model weights would have to be loaded every time.

**Comment by amueller** [comment]
Thank you for your quick response.
Using scikit-learn cross-validation, you'd have to reload the model every time probably. I think TabPFN got around that by using a cache. Re ``cat_features`` I'd still try to avoid using mutable defaults, most linters will warn about it since it's easy to get very tricky bugs.

**Comment by davidbonet** [comment]
Hey,

Thanks for the feedback. We took your suggestions and moved `cat_features` to `__init__` and avoided mutable defaults. We also implemented the caching mechanism, which should now allow smoother runs!

Make sure to install the new release [v1.0.0](https://github.com/AI-sandbox/HyperFast/releases/tag/v1.0.0).
