### ISSUE TITLE
Supporting categorical variables encoded as strings

### ISSUE THREAD

**Issue by amueller** [AI-sandbox/HyperFast#5]
Hey!
So are you supporting categorical variables that are encoded as strings? Because the current code doesn't look like it does. Thanks!

**Comment by davidbonet** [comment]
Hey, good catch! Actually, the very first commit supported categorical variables encoded as strings, but didn't completely satisfy the sklearn API. When we changed that, we only checked for numerical values. cc1349d now fixes that while being sklearn safe :)

**Comment by amueller** [comment]
great, thank you!
