### ISSUE TITLE
Enforce training and inference time limit like in the paper?

### ISSUE THREAD

**Issue by bruder-grimm** [AI-sandbox/HyperFast#6]
Hello 👋

Is there a way to programmatically enforce a strict runtime limit like it was used in the paper to evaluate against other methods? I cannot seem to find such a functionality in the code.

Best

**Comment by davidbonet** [comment]
Hi,

HyperFast doesn't include a functionality for setting a strict runtime limit. However, both for HyperFast and other non-AutoML models, you can achieve this with hyperparameter optimization tools such as Hyperopt, which was used in our experiments.

Best,
David
